ARR: 0.0
adj_dropout: 0.2
force_undirected: false
latent_dim:
- 32
- 32
- 32
- 32
lr: 0.001
lr_decay_factor: 0.1
lr_decay_step_size: 50
n_side_features: 0
num_bases: 4
num_features: 4
num_layers: 4
num_relations: 1
use_features: false
